version: "3.7"

services:
  mc:
    image: itzg/minecraft-server
    ports:
    - 25565:25565
    - 8123:8123
    environment:
      EULA: "TRUE"
      VERSION: 1.16.4
      DIFFICULTY: normal
      SERVER_NAME: AzunyanServer
      TYPE: FORGE
      FORGEVERSION: 35.1.32
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      TZ: Asia/Tokyo
      ENABLE_RCON: "true"
      RCON_PASSWORD: "moyashi3104"
      RCON_PORT: 28016
      ENABLE_QUERY: "true"
      ENABLE_STATUS: "true"
      OPS: pitekusu
      USE_AIKAR_FLAGS: "true"
      MEMORY: 14G
      USE_LARGE_PAGES: "true"
      VIRTUAL_HOST: dynmap.azunyan.io
      VIRTUAL_PORT: 8123
      LETSENCRYPT_HOST: dynmap.azunyan.io
      LETSENCRYPT_EMAIL: pitekusu@gmail.com

    tty: true
    stdin_open: true
    restart: always

    volumes:
    - mc_forge:/data
    - ./mods:/mods:ro

volumes:
  mc_forge: {}

networks:
  default:
    external:
      name: nginx-proxy
